# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Elisa Aprà
tagline:             designer, student, pasta enthusiast
url:                 elisaapra.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Elisa Aprà
  url:               https://instagram.com/gracidea
  email:             elisa.apra@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole
